---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  tasks: 
    - name: Get service name
      win_service:
      register: win*

    - name: Show output
      debug:
        var: win*
      
...
